---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2025.3.4

    env:
      TZ: "America/New_York"
      PYTHONPATH: "/config/deps"
      UV_SYSTEM_PYTHON: "true"
      UV_NO_CACHE: "true"

    envFrom:
      - secretRef:
          name: home-assistant-secret

    # required for mDNS and other host network features
    hostNetwork: true

    dnsPolicy: ClusterFirstWithHostNet

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 10.0.5.56 # TODO: change this once old cluster is removed
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        # ensure that external DNS (cloudflare) has an entry for this directed to the router
        # ensure that internal DNS for this zone (coredns) has an entry for this directed to nginx LB IP
        ingressClassName: nginx-tailscale # TODO: change this once old cluster is removed
        hosts:
          - host: &host hass.t.eviljungle.com # TODO: change this once old cluster is removed
            paths:
              - path: /
        tls:
          - hosts:
              - *host
      # tailscale:
      #   enabled: true
      #   ingressClassName: nginx-tailscale # TODO: change this once old cluster is removed
      #   hosts:
      #     - host: *host
      #       paths:
      #         - path: /
      #           pathType: Prefix
      #   tls:
      #     - hosts:
      #         - *host

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true

    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: "5Gi" # TODO: change this to 60Gi whence old cluster is removed
      hass-gcp-sa-json:
        enabled: true
        type: secret
        name: home-assistant-gcp-sa-secret
        subPath: home-assistant-4d8d1f2ca10f.json
        mountPath: /config/home-assistant-4d8d1f2ca10f.json
        readOnly: true
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
      docker-env-empty:
        enabled: true
        type: emptyDir
        subPath: .dockerenv
        mountPath: /.dockerenv
        readOnly: true

    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        memory: 2048M

    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.98.2
        workingDir: "/config"
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
          - --auth
          - "none"
        env:
          TZ: America/New_York
          HASS_SERVER: http://localhost:8123
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          fsGroupChangePolicy: "OnRootMismatch"
        ingress:
          enabled: true
          ingressClassName: nginx-tailscale
          annotations:
            nginx.ingress.kubernetes.io/custom-http-errors: "500,502,503,504"  # Using only 5xx custom error pages
          hosts:
            - host: hass-vscode.t.eviljungle.com # TODO: change this once old cluster is removed
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - hass-vscode.t.eviljungle.com # TODO: change this once old cluster is removed
        volumeMounts:
        - name: config
          mountPath: /config
