---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: datasource=github-releases depName=external-secrets/external-secrets
  - https://github.com/external-secrets/external-secrets/raw/v0.15.0/deploy/crds/bundle.yaml
  # renovate: datasource=github-releases depName=kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter/raw/v8.2.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  # renovate: datasource=github-releases depName=kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter/raw/v8.2.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
  # renovate: datasource=github-releases depName=kubernetes-csi/external-snapshotter
  - https://github.com/kubernetes-csi/external-snapshotter/raw/v8.2.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  # renovate: datasource=github-releases depName=backube/volsync
  - https://github.com/backube/volsync/raw/v0.12.0/config/crd/bases/volsync.backube_replicationdestinations.yaml
  # renovate: datasource=github-releases depName=backube/volsync
  - https://github.com/backube/volsync/raw/v0.12.0/config/crd/bases/volsync.backube_replicationsources.yaml
  # renovate: datasource=github-releases depName=kubernetes-sigs/node-feature-discovery
  - https://github.com/kubernetes-sigs/node-feature-discovery/raw/v0.17.2/deployment/helm/node-feature-discovery/crds/nfd-api-crds.yaml
  