---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager.yaml
  - ./prometheusRule.yaml
configMapGenerator:
  - name: cert-manager-helm-values
    files:
      - values.yaml=./values.yaml
configurations:
  - |
    nameReference:
      - kind: ConfigMap
        version: v1
        fieldSpecs:
          - path: spec/valuesFrom/name
            kind: HelmRelease