---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: home-cluster
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  exclusionList:
    - "error.*lookup github\\.com"
    - "error.*lookup raw\\.githubusercontent\\.com"
    - "dial.*tcp.*timeout"
    - "waiting.*socket"
    - "snapshot-controller configured"
    - "snapshot-validation-webhook configured"
    - "volsync configured"
    - "Health check passed in"
    - "Dependencies do not meet ready condition, retrying in 30s"
    - "read: connection timed out"
    - "GitRepository/flux-system/flux-system configured"
    - "kustomization/core-crds.flux-system"
  suspend: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helmreleases
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: HelmRelease
      namespace: 'default'
      name: '*'
    - kind: HelmRelease
      namespace: 'flux-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'logs'
      name: '*'
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'monitoring'
      name: '*'
    - kind: HelmRelease
      namespace: 'network'
      name: '*'
    - kind: HelmRelease
      namespace: 'rook-ceph'
      name: '*'
  suspend: false
