---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: 1password-charts
        namespace: flux-system
      interval: 5m
  values:
    namespace: kube-system
    connect:
      credentialsName: onepassword-secret
      credentialsKey: token
    operator:
      create: false
    serviceType: ClusterIP
