---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 30m
  values:
    installCRDs: true
    replicaCount: 1
    serviceMonitor:
      enabled: true
    webhook:
      serviceMonitor:
        enabled: true
    certController:
      serviceMonitor:
        enabled: true
