---
clusterName: home
endpoint: https://10.2.0.50:6443
additionalApiServerCertSans:
  - k8s-0
  - k8s-0.home
  - k8s-0.drake-eel.ts.net
cniConfig:
  name: none
nodes:
  - hostname: k8s-0
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: true
    ipAddress: 10.2.0.50
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true
  - hostname: k8s-a
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: false
    ipAddress: 10.2.0.51
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, more speed
        - init_on_alloc=0 # Less security, more speed
        - init_on_free=0 # Less security, more speed
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, more speed
        - security=none # Less security, more speed
        - talos.auditd.disabled=1 # Less security, more speed
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/qemu-guest-agent
          # - siderolabs/tailscale
  # extensionServices:
  # - name: tailscale
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  patches:
    # Configure cluster
    - |-
      cluster:
        allowSchedulingOnControlPlanes: false
        coreDNS:
            disabled: true
        proxy:
          disabled: true
        scheduler:
          config:
            apiVersion: kubescheduler.config.k8s.io/v1
            kind: KubeSchedulerConfiguration
            profiles:
              - schedulerName: default-scheduler
                pluginConfig:
                  - name: PodTopologySpread
                    args:
                      defaultingType: List
                      defaultConstraints:
                        - maxSkew: 1
                          topologyKey: kubernetes.io/hostname
                          whenUnsatisfiable: ScheduleAnyway

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_user_watches: 1048576   # Watchdog
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC
          net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet

    # Disable default API server admission plugins.
    # - |-
    #   - op: remove
    #     path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - system-upgrade

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false

worker:
  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0 # Less security, more speed
        - init_on_alloc=0 # Less security, more speed
        - init_on_free=0 # Less security, more speed
        - intel_iommu=on # PCI Passthrough
        - iommu=pt # PCI Passthrough
        - mitigations=off # Less security, more speed
        - security=none # Less security, more speed
        - talos.auditd.disabled=1 # Less security, more speed
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/qemu-guest-agent
  patches:
    # Configure NFS mount options
    - |
      machine:
        files:
          - op: overwrite
            path: /etc/nfsmount.conf
            permissions: 0o644
            content: |
              [ NFSMount_Global_Options ]
              nfsvers=4.2
              hard=True
              noatime=True
              nconnect=16

    # Configure custom sysctls
    - |-
      machine:
        sysctls:
          fs.inotify.max_user_instances: 8192    # Watchdog
          fs.inotify.max_user_watches: 1048576   # Watchdog
          net.core.rmem_max: 67108864            # Cloudflared / QUIC
          net.core.wmem_max: 67108864            # Cloudflared / QUIC
          net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet
          vm.nr_hugepages: 1024                  # PostgreSQL

    # Configure udev rules
    - |-
      machine:
        udev:
          rules:
            # Intel GPU
            - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
            # Coral Edge M.2 TPU
            - SUBSYSTEM=="apex", KERNEL=="apex*", GROUP="44", MODE="0660"

    # Enable host dns
    - |-
      machine:
        features:
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
