# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.5
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.3

clusterName: home
endpoint: https://k8s-0:6443

additionalApiServerCertSans:
  - k8s-0
  - k8s-0.home
  - k8s-0.drake-eel.ts.net

# Disable built-in Flannel to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: k8s-0
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: true
    ipAddress: 10.2.0.50
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true
  - hostname: k8s-a
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: false
    ipAddress: 10.2.0.51
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true
  - hostname: k8s-b
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: false
    ipAddress: 10.2.0.52
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true
  - hostname: k8s-c
    nodeAnnotations:
      installerImage: '{{ .MachineConfig.MachineInstall.InstallImage }}'
    controlPlane: false
    ipAddress: 10.2.0.53
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:*
        dhcp: true

# Global patches
patches:
  - "@./patches/global/machine-dns.yaml"     # Host DNS settings
  - "@./patches/global/machine-files.yaml"   # Spegel/NFS Mount
  - "@./patches/global/machine-install.yaml" # Less security, more performance
  - "@./patches/global/machine-network.yaml" # Search Domain
  - "@./patches/global/machine-sysctls.yaml" # Network Tweaks
  - "@./patches/global/machine-udev.yaml"    # udev settings

controlPlane:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/qemu-guest-agent
          # - siderolabs/tailscale
  # extensionServices:
  # - name: tailscale
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  patches:
    - "@./patches/controller/admission-controller-patch.yaml" # makes rook-ceph work
    - "@./patches/controller/cluster.yaml" 
    - "@./patches/controller/machine-features.yaml"

worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/qemu-guest-agent
